"""Cut the narration take into its lines and lay them on the picture's timeline.

  python3 tools/vo.py narration.mp3        (FFMPEG=... if ffmpeg is not on PATH)

The take is one file with every line, separated by pauses. The lines are found by
silence, trimmed, nudged faster when a line is longer than its slot (up to 1.2x),
and placed at the slot's start. Output: js/vo.js, which carries the 15 s narration
track (Opus, base64) and the spoken spans that js/audio.js ducks the music under.
"""
import base64, json, os, subprocess, sys, tempfile
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
FFMPEG = os.environ.get("FFMPEG", "ffmpeg")
SR = 48000
# (line, slot start, latest end) — where each line sits in the 15 s cut
SLOTS = [
    ("恋する乙女は、痩せて、最高の私へ。", 0.12, 1.98),
    ("今日から、私の未来が、変わりはじめる。", 2.12, 3.72),
    ("なんで私って、こうなんだろう。", 5.78, 7.38),
    ("わたしを、あきらめない。", 7.56, 9.0),
    ("次の駅は、理想の私。", 9.42, 10.5),
    ("一緒に、乗り越えよう。", 10.52, 11.75),
    ("女性専用パーソナルジム、エトワール。", 11.98, 13.55),
    ("無料カウンセリング、受付中。", 13.6, 14.96),
]


def decode(path, filters=None):
    cmd = [FFMPEG, "-loglevel", "error", "-i", str(path)] + (["-af", filters] if filters else []) + \
          ["-ac", "1", "-ar", str(SR), "-f", "f32le", "-"]
    return np.frombuffer(subprocess.run(cmd, capture_output=True, check=True).stdout, np.float32).copy()


def spans(x, n):
    """The n loudest-separated speech spans: frames above -42 dB of peak, gaps merged."""
    hop = SR // 100
    env = np.sqrt(np.convolve(x ** 2, np.ones(hop) / hop, "same"))[::hop]
    on = env > np.max(env) * 10 ** (-42 / 20)
    idx = np.nonzero(np.diff(np.r_[0, on.astype(int), 0]))[0].reshape(-1, 2)  # [start, end) in 10 ms frames
    segs = [list(s) for s in idx if s[1] - s[0] > 4]
    while len(segs) > n:  # merge across the shortest gap (a comma, not a line break)
        g = int(np.argmin([segs[i + 1][0] - segs[i][1] for i in range(len(segs) - 1)]))
        segs[g][1] = segs[g + 1][1]; del segs[g + 1]
    if len(segs) != n:
        sys.exit(f"found {len(segs)} lines, expected {n}")
    return [(max(0, a - 3) * hop, min(len(x), (b + 4)) * hop) for a, b in segs]  # 30 ms lead-in, 40 ms tail


def main(src):
    x = decode(src, "highpass=f=80,lowpass=f=15000")
    track = np.zeros(int(SR * 15), np.float32)
    placed = []
    with tempfile.TemporaryDirectory() as tmp:
        for (text, t0, t1), (a, b) in zip(SLOTS, spans(x, len(SLOTS))):
            seg = x[a:b]
            dur = len(seg) / SR
            k = max(1.0, dur / (t1 - t0))
            if k > 1.2:
                print(f"! {text}: {dur:.2f}s does not fit {t1 - t0:.2f}s even at 1.2x — it will run over")
                k = 1.2
            if k > 1.0:  # tempo change without pitch change
                p = Path(tmp) / "seg.f32"
                seg.tofile(p)
                seg = np.frombuffer(subprocess.run([FFMPEG, "-loglevel", "error", "-f", "f32le", "-ar", str(SR), "-ac", "1", "-i", str(p),
                                                   "-af", f"atempo={k:.4f}", "-f", "f32le", "-"], capture_output=True, check=True).stdout, np.float32)
            fade = int(SR * 0.012)
            seg = seg.copy(); seg[:fade] *= np.linspace(0, 1, fade); seg[-fade:] *= np.linspace(1, 0, fade)
            i0 = int(t0 * SR); i1 = min(len(track), i0 + len(seg))
            track[i0:i1] += seg[: i1 - i0]
            placed.append([round(t0, 3), round(i1 / SR, 3)])
            print(f"{t0:5.2f}–{i1 / SR:5.2f}  x{k:.2f}  {text}")
        track /= max(1e-6, np.max(np.abs(track))) / 0.89  # peak −1 dBFS; audio.js sets the level against the music
        raw = Path(tmp) / "vo.f32"; track.tofile(raw)
        enc = Path(tmp) / "vo.ogg"
        subprocess.run([FFMPEG, "-loglevel", "error", "-y", "-f", "f32le", "-ar", str(SR), "-ac", "1", "-i", str(raw),
                        "-c:a", "libopus", "-b:a", "96k", str(enc)], check=True)
        b64 = base64.b64encode(enc.read_bytes()).decode()
    (ROOT / "js" / "vo.js").write_text(
        "// Narration (generated by tools/vo.py): a 15 s Opus track and the spans the music ducks under.\n"
        f"window.ETOILE_VO = {{ spans: {json.dumps(placed)}, data: \"{b64}\" }};\n")
    print("wrote js/vo.js", len(b64) // 1024, "KB")


if __name__ == "__main__":
    main(sys.argv[1])
